# Generated by Django 5.1.1 on 2024-10-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_Completes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecompletes',
            name='profile_photo',
            field=models.BooleanField(default=False),
        ),
    ]
