# Generated by Django 5.1.1 on 2024-10-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_Completes', '0002_alter_profilecompletes_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileCompletes',
        ),
    ]
