# Generated by Django 5.1.1 on 2024-10-07 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile_Completes', '0003_delete_profilecompletes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCompletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.BooleanField(default=False)),
                ('basic_details_completed', models.BooleanField(default=False)),
                ('education_details_completed', models.BooleanField(default=False)),
                ('horoscope_details_completed', models.BooleanField(default=False)),
                ('family_details_completed', models.BooleanField(default=False)),
                ('partner_preference_details_completed', models.BooleanField(default=False)),
                ('habbits_interests_details_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_completion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
