# Generated by Django 5.1.1 on 2024-10-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_Completes', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileCompletes',
        ),
    ]
