# Generated by Django 5.0.3 on 2024-10-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabbitsInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(max_length=255)),
                ('movie', models.CharField(max_length=255)),
                ('books', models.CharField(max_length=255)),
                ('travel', models.CharField(max_length=255)),
                ('volunteer_work', models.CharField(max_length=255)),
                ('cooking', models.CharField(max_length=255)),
                ('music', models.CharField(max_length=255)),
                ('writing', models.CharField(max_length=255)),
                ('gaming', models.CharField(max_length=255)),
                ('gardening', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habbits_interest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
