# Generated by Django 5.0.3 on 2024-10-21 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habbits_Interest_App', '0002_alter_habbitsinterest_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbitsinterest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habbits_interest', to=settings.AUTH_USER_MODEL),
        ),
    ]
