# Generated by Django 5.1.1 on 2024-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile_App', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
