# Generated by Django 5.0.3 on 2024-10-03 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPreferenceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=20)),
                ('age_from', models.PositiveIntegerField()),
                ('age_to', models.PositiveIntegerField()),
                ('height_from', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height_to', models.DecimalField(decimal_places=2, max_digits=4)),
                ('religion', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('complexion', models.CharField(max_length=100)),
                ('residency_status', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('partner_expectations', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
