# Generated by Django 5.1.1 on 2024-10-01 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_sign', models.CharField(max_length=20)),
                ('star', models.CharField(max_length=20)),
                ('gotra', models.CharField(max_length=50)),
                ('manglik', models.BooleanField(default=False)),
                ('shani', models.BooleanField(default=False)),
                ('horoscope_match', models.BooleanField(default=False)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('place_of_country', models.CharField(max_length=100)),
                ('hours', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('seconds', models.PositiveIntegerField()),
                ('AM_PM', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horoscope_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
