# Generated by Django 5.1.1 on 2024-10-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoroscopeDetails_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopedetails',
            name='horoscope_match',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horoscopedetails',
            name='manglik',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horoscopedetails',
            name='shani',
            field=models.CharField(max_length=100),
        ),
    ]
