# Generated by Django 5.0.3 on 2024-10-21 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoroscopeDetails_App', '0003_alter_horoscopedetails_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscopedetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horoscope_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
