# Generated by Django 5.1.1 on 2024-10-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('alt_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('convenient_time_to_call', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('show_permanent_address', models.TextField()),
                ('show_working_address', models.TextField()),
            ],
        ),
    ]
