# Generated by Django 5.1.1 on 2024-10-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternative_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('convenient_time_to_call', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('show_permanent_address', models.TextField()),
                ('show_working_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
